# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      pwd
      ls

- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'sonarcloud'
    organization: 'silencfox'
    scannerMode: 'cli'
    configMode: 'file'

- task: SonarCloudAnalyze@3
  enabled: false
  inputs:
    jdkversion: 'JAVA_HOME'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
