# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  name: myAgents
  demands:
  - Agent.Name -equals AgnLapwrk02
  #vmImage: windows-latest

steps:



- checkout: self
  persistCredentials: true
  clean: true
  fetchDepth: 0


- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'

- task: InstallTestCompleteAdapter@1
  enabled: true
  inputs:
    installExecutor: false
    updateExecutor: false
    logsLevel: '0'
    exportLog: true
    junitLog: true   # <--- ESTO genera el JUnit XML
    #cmdLineParams: '/PrjVar:UserName="adam.smith"'
    #preferredExecutor: TE

- task: InstallTestCompleteAdapter@1
  enabled: false
  inputs:
    preferredExecutor: 'TC32bit'
    installExecutor: true
    updateExecutor: false
    searchMode: 'ProjectItems'
    logsLevel: '0'
    projectSuite: '$(Build.SourcesDirectory)/test/TestProject1/TestProject1.pjs'
    logExportPath: '$(Build.ArtifactStagingDirectory)/TestCompleteLogs'
    exportLog: true
    junitLog: true   # <--- ESTO genera el JUnit XML

- task: VSTest@2
  enabled: false
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\*.pjs'
    searchFolder: '$(System.DefaultWorkingDirectory)/test/TestProject1'
    #testFiltercriteria: 'Test=ProjectTestItem1'
    vsTestVersion: 'toolsInstaller'
    pathtoCustomTestAdapters: '$(System.DefaultWorkingDirectory)/TestCompleteAdapter'
    testRunTitle: 'Automated tests'


- task: CmdLine@2
  displayName: 'Ejecutar pruebas TestComplete 01'
  inputs:
    script: |
      "C:/Program Files/SmartBear/TestExecute 15/Bin/TestExecute.exe" "$(System.DefaultWorkingDirectory)/test/TestProject1/TestProject1.pjs" /run /project:"NombreDelProyecto" /test:"NombreDelTest" /exportlog:"$(Build.ArtifactStagingDirectory)/ExportedLog.mht" /silentmode /exit



- task: CmdLine@2
  displayName: 'Ejecutar pruebas TestComplete'
  inputs:
    script: |
      "C:/Program Files/SmartBear/TestComplete 15/bin/TestComplete.exe" "$(System.DefaultWorkingDirectory)/test/TestProject1/TestProject1.pjs" /run /SilentMode /ExportLog:"$(Build.ArtifactStagingDirectory)/TestLog.mht" /ErrorLog:"$(Build.ArtifactStagingDirectory)/ErrorLog.txt" /exit

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'TestCompleteLogs'

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
    workingDirectory: '$(System.DefaultWorkingDirectory)'