apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  #name: {{ include "Devsu_chart.fullname" . }}
  labels:
    {{- include "Devsu_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: http
  selector:
    name: {{ .Release.Name }}
