apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/silencfox/Dev_Project.git
    path: deployment/NewServices
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: NewServices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true