apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app-v2
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
