apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service
  namespace: devsu
spec:
  selector:
    matchLabels:
      run: node-service  # Cambiado de desunode a node-service
  replicas: 2
  template:
    metadata:
      labels:
        run: node-service  # Cambiado de desunode a node-service
    spec:
      containers:
      - name: node-service  # Cambiado de desunode a node-service
        image: silencfox/devsudemo:512
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 100Mi

        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /api/users
            port: 8000
      automountServiceAccountToken: false
