apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-service  # Cambiado de desunode a node-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
