apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-letsencrypt
  namespace: cert-manager
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10" # Menor peso = se ejecuta antes
spec:
  acme:
    # The ACME server URL
    #server: https://acme-v02.api.letsencrypt.org/directory
    server: {{ $.Values.cert.acme.server }}
    # Email address used for ACME registration
    email: {{ $.Values.cert.acme.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx