---
{{- $root := . }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $root.Release.Name }}-ing
  annotations:
    cert-manager.io/cluster-issuer: staging
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ $root.Values.ingress.className }}
  rules:
    - host: echo.kdvops.com
      http:
        paths:
          {{- range $i := until (.Values.service.count | int) }}
          - path: {{ $root.Values.ingress.hosts.path }}{{ add $i 1 }}(/|$)(.*)
            pathType: {{ $root.Values.ingress.hosts.pathType }}
            backend:
              service: 
                name: {{ printf "%s-svc%d" $root.Release.Name (add $i 1) }}
                port:
                  number: {{ $root.Values.image.port }}
          {{- end }}

  tls:
    - hosts:
        - echo.kdvops.com
      secretName: echo-kdvops-com
---

{{- end }}