---
{{- $root := . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  annotations:
    cert-manager.io/cluster-issuer: staging
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ $root.Values.ingress.className }}
  rules:
    - host: echo.kdvops.com
      http:
        paths:
          - path: /v1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-svc
                port:
                  number: {{ $root.Values.image.port }}
          - path: /v2(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: echoserver-v2-1-secure
                port:
                  number: {{ $root.Values.image.port }}
  tls:
    - hosts:
        - echo.kdvops.com
      secretName: echo-kdvops-com
