apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: svc1.kdvops.com
    http:
      paths:
      - path: /v1
        pathType: Exact
        backend:
          service:
            name: devsudemo-svc1
            port:
              number: 80
        
  - host: svc2.kdvops.com
    http:
      paths:
      - path: /v2
        pathType: Exact
        backend:
          service:
            name: devsudemo-svc2
            port:
              number: 80