---
{{- $root := . }}
{{- if and (eq .Values.cloudProvider "azure") .Values.storageClass.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClass.name }}
  resources:
    requests:
      storage: 5Gi
---
{{- end }}      