apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  USER: {{ .Values.secret.username | b64enc | quote }}
  PASS: {{ .Values.secret.password | b64enc | quote }}
  DATABASE: {{ .Values.secret.database | b64enc | quote }}  