{{- $root := . }}
{{- if .Values.service.enabled }}
{{- range $i := until (.Values.service.count | int) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc%d" $root.Release.Name (add $i 1) }}
  labels:
    {{- include "devsudemo.labels" $root | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5" # Menor peso = se ejecuta antes
spec:
  type: {{ $root.Values.service.type }}
  ports:
    - port: {{ $root.Values.service.port }}
      targetPort: {{ $root.Values.image.port }}
      protocol: TCP
      name: http
  selector:
    name: {{ $root.Release.Name }}
---
{{- end }}
{{- end }}
