apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-local-cert
  #namespace: tu-namespace
spec:
  commonName: v1.devsu.local
  dnsNames:
  - v1.devsu.local
  - v2.devsu.local
  secretName: dev-local-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
